# Generated by Django 5.2.12 on 2026-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='events/')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('max_guests', models.PositiveIntegerField(default=0, help_text='0 = без ограничения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_start'],
                'indexes': [models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'), models.Index(fields=['is_published', 'date_start'], name='events_even_is_publ_31ad29_idx')],
            },
        ),
    ]
