# Generated by Django 5.2.12 on 2026-03-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.PositiveIntegerField(default=0, help_text='Вес в граммах')),
                ('photo', models.ImageField(blank=True, upload_to='menu/')),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.category')),
            ],
            options={
                'ordering': ['category__sort_order', 'category__name', 'name'],
                'indexes': [models.Index(fields=['slug'], name='menu_dish_slug_356d63_idx'), models.Index(fields=['is_active', 'category'], name='menu_dish_is_acti_4e273a_idx'), models.Index(fields=['name'], name='menu_dish_name_6ad09b_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='uniq_dish_name_per_category')],
            },
        ),
    ]
