# Generated by Django 5.2.12 on 2026-05-31

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(default="Йошкар-Ола, ул. Ленина, 1", max_length=255, verbose_name="Адрес")),
                ("phone", models.CharField(default="8 800 555-35-35", max_length=64, verbose_name="Телефон")),
                (
                    "working_hours",
                    models.CharField(default="ежедневно 10:00–23:00", max_length=120, verbose_name="Часы работы"),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Скопируйте src из iframe: Яндекс.Карты → Поделиться → Код для сайта. Если оставить пустым, карта строится по координатам ниже.",
                        max_length=500,
                        verbose_name="Ссылка для встраивания карты",
                    ),
                ),
                (
                    "map_longitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("47.894742"),
                        max_digits=9,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "map_latitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("56.634407"),
                        max_digits=9,
                        verbose_name="Широта",
                    ),
                ),
                ("map_zoom", models.PositiveSmallIntegerField(default=16, verbose_name="Масштаб")),
            ],
            options={
                "verbose_name": "Контакты и карта",
                "verbose_name_plural": "Контакты и карта",
            },
        ),
    ]
