# Generated by Django 5.2.12 on 2026-03-17 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('visit_counted', 'Засчитан визит'), ('event_registered', 'Запись на мероприятие'), ('event_cancelled', 'Отмена записи'), ('review_created', 'Отправлен отзыв')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_opera_user_id_04f39c_idx')],
            },
        ),
    ]
