# Generated by Django 5.2.12 on 2026-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_visit_counted',
            field=models.BooleanField(default=False, help_text='Отмечается автоматически при подтверждении, чтобы не засчитывать посещение дважды.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма чека (для накопительной скидки). Можно заполнить позже в админке.', max_digits=12),
        ),
    ]
