# Generated by Django 5.2.12 on 2026-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('interior', 'Интерьер'), ('food', 'Еда'), ('event', 'События')], default='interior', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', 'category'], name='gallery_gal_is_publ_ce614e_idx')],
            },
        ),
    ]
